### ISSUE TITLE
`ampersand` hangs after author name prompt

### ISSUE THREAD

**Issue by zeke** [AmpersandJS/ampersand#112]
I made it this far:

```
» ampersand
ampersand.js - app generator

This will make a new directory for your app in:
/Users/z/Desktop

? What do you want to call the folder? ampy
? What is the human friendly title of your app? Ampy
? Do you want to use hapi or express as a server framework? hapi
? What's your name? Used to populate "author" field of "package.json", as:

{
  "name": "app",
  "version": "0.0.1",
  "author": "Your answer",
  "dependencies": ...
}

Author Name: Zeke
```

^ The process hangs here, then my fans start spinning.

```
» which node
/Users/z/.nvm/versions/io.js/v1.5.1/bin/node
```

**Comment by zeke** [comment]
I just went through the same process on node 0.10.35, and it worked like a charm.

This may be a duplicate of https://github.com/AmpersandJS/ampersand/issues/105

**Comment by fyockm** [comment]
@zeke I can confirm that the process hangs with `iojs-v1.5.1` and `iojs-v1.6.2`. However, it seems to work fine with node `v0.10.38` and `v0.12.1`. Not sure what the problem is, but I don't think it's related to #105.

For now, I would recommend just using a version of `node` instead of `iojs`.

**Comment by fyockm** [comment]
@zeke Re-reading #105, I realized that the issue described by @therebelrobot is actually the same as you mention here. However, the purpose of that issue was different, which is why I claimed them unrelated. Sorry for the confusion.

**Comment by zeke** [comment]
No worries. Feel free to close if this is indeed a dupe..

**Comment by chiarishow** [comment]
+1

same problem here with MacOSX with iojs and yosemite. 

generation stuck after Author Name.

**Comment by fyockm** [comment]
Even with the fix for #105, there still seems to be a problem with `iojs`. I've tested successfully on `node@12.2`. Need to dig a little deeper.

**Comment by hermwong** [comment]
This is happening for me using:

```
node -v
v1.8.1
```

and also with:

```
iojs -v
v1.8.1
```

**Comment by DimitryDushkin** [comment]
Same on iojs 2.5.0

**Comment by agentS** [comment]
Same with iojs 2.3.4 and node 4 on a 64 bit Linux OS.

**Comment by HenrikJoreteg** [comment]
The issue seems to be with the `ncp` module, which appears to have issues in node 4. The callback never gets called after this call: https://github.com/AmpersandJS/ampersand/blob/master/lib/app/generateApp.js#L38 that copies the template directory.

There's an alternative module that does the same called CPR: https://github.com/davglass/cpr that would probably work but lacks the transform option so the transform would have to be done separately.

**Comment by HenrikJoreteg** [comment]
this may be a better alternative, i've used this module in the past: https://www.npmjs.com/package/fs-extra#copy and it sees quite a bit of use.

**Comment by fyockm** [comment]
Thanks for doing the legwork @HenrikJoreteg! I like your solution because `fs-extra` is already being used in this module. I'll submit a PR for review shortly.
