### ISSUE TITLE
Consider a monorepo

### ISSUE THREAD

**Issue by callumlocke** [AmpersandJS/ampersand#120]
I've just read Babel's reasons for [having a monorepo](https://github.com/babel/babel/blob/master/doc/design/monorepo.md) (and some of the discussions linked from the bottom of that page), and it struck me that this might be a good strategy for AmpersandJS too.

If this idea has been discussed already then please close this.

**Comment by cdaringe** [comment]
please ref https://github.com/AmpersandJS/ampersand-state/issues/219
