### ISSUE TITLE
CLI generator override?

### ISSUE THREAD

**Issue by kokujin** [AmpersandJS/ampersand#13]
Is there a way to use the Ampersand generator to create models, forms e.t.c. in the curenbt directory? I read about configuring the .ampersandrc file but thats bothersome to do everytime, and actually, withput a prompt, it should use the current directoy as default like other generators( Express, Sails.js ) instead of :

````
../../../client/models/app/user.js
````

Thanks

**Comment by e2jk** [comment]
Just wondering, as this issue was opened withing the first month of the project being created: does this issue/wish still exist?

**Comment by HenrikJoreteg** [comment]
wow, this has been sitting for some time. Apologies. Just for the record, in case anyone finds this through google or it's still relevant. This can be done with overrides as follows: 

```
ampersand gen model {{item}} --clientfolder src --modelfolder models
```
