### ISSUE TITLE
Implement demo pagination in demo collection

### ISSUE THREAD

**Issue by distilledhype** [AmpersandJS/ampersand#18]
Filing this bug as requested by @HenrikJoreteg: https://twitter.com/henrikjoreteg/status/487240149864951808

Implement a pagination example of how to best do that with an AmpersandJS collection.
Perhaps with ampersand-subcollection? How do you do routing for the pagination?

As a bonus, it would be great to see more examples of how to use subcollection cleanly for other use cases, for instance with endless scrolling or a filtering use case.

Thanks!

**Comment by HenrikJoreteg** [comment]
At this point we've decided to make the generated app lightweight instead of adding extras like this. This kind of thing could/should be done in https://github.com/ampersandjs/examples.

**Comment by distilledhype** [comment]
NIce!
