### ISSUE TITLE
HTMLAnchorElement.host cross-browser issues

### ISSUE THREAD

**Issue by lukekarrys** [AmpersandJS/ampersand#27]
https://github.com/AmpersandJS/ampersand/blob/9ccb13a4fc6e9f0a1008a525edecbc1d30162611/template/shared/client/views/main.js#L62

That link won't yield the expected results in IE9 since (from [this post](http://blogs.msdn.com/b/ieinternals/archive/2011/02/28/internet-explorer-window-location-pathname-missing-slash-and-host-has-port.aspx))

> Specifically, the host property sometimes includes the port number (even when that port is the default port for the scheme)

**Comment by lukekarrys** [comment]
We're using `[local-links](https://github.com/lukekarrys/local-links)` now so this is fixed.

**Comment by HenrikJoreteg** [comment]
thanks @lukekarrys!
