### ISSUE TITLE
link browserify debug to developmentMode

### ISSUE THREAD

**Issue by flipside** [AmpersandJS/ampersand#80]
I've been experimenting with an express app and a hapi app but it took me forever to figure out how to turn on the sourceMap for the hapi app because it did not have the default moonboots config:

    browserify: {
        debug: false
    }

Is there a reason why debug should be false in developmentMode? If not, they can easily be linked in config via:

    browserify: {
        debug: config.isDev
    }

If there is a reason to not link debug and dev, then adding a default browserify config to the hapi would be the next best thing.

**Comment by fyockm** [comment]
:+1: I did exactly the same in my project

**Comment by fyockm** [comment]
Actually, my change is for `express`, not `hapi`? Looks like there isn't a `browserify` option in the hapi moonboots config?

**Comment by flipside** [comment]
Yep, missing browserify option. Actually, the whole hapi setup could be upgraded to hapi ^8.0.0.

**Comment by fyockm** [comment]
Upgrade to Hapi 8.0.0 was just merged today, see f2fa00c07dbe1556c108fcfe2d35fafd0bce9eac.

I'll update #88 to add the `browersify` option for hapi.
