### ISSUE TITLE
global link click listener steals middle-clicks

### ISSUE THREAD

**Issue by chesles** [AmpersandJS/ampersand#86]
Related to a few other issues (#3, #71) - middle clicks are hijacked by the app by default when they should be opened in a new tab.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/event.button) a check for `event.button == 0` would let us capture only left-click or "standard" clicks, allowing middle clicks to be handled by the browser. As of IE9 it looks like this convention is followed by all browsers (before that it was [a bit of a mess](http://www.quirksmode.org/js/events_properties.html#button), apparently).

**Comment by lukekarrys** [comment]
I create the module [local-links](https://www.npmjs.org/local-links) to handle stuff like this and it is now being used in the template. I just tested in an ampersand app that uses local-links, and middle click now works as expected.
