### ISSUE TITLE
Lead maintainers

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersand#95]
It would help each module if someone was nominally tagged as 'Lead' on them.  This would help contributors and users feel like they know who to reach out to for issues and help, and also would allow that person to feel more empowered to make decisions and keep up on issues for those modules.

This issue is for discussion of this idea, and if it's generally accepted, assigning these roles to each module.

Assigning a lead does not remove any other core contributor's privileges or grant that lead more privileges than any other core contributor for that module, bug triage rules still apply.

Leads would not necessarily need to be core contributors, and this would be a great way to get people who have helped with specific modules the ability to 'take the reigns' on them a little more.

The lead maintainer would be added to the header of the module readme w/ a link to their github profile.

Leads must be assigned with the consent of the person being assigned.

The [bug triage process](https://ampersandjs.com/learn/bug-triage-process) will need to include lead roles in the event that they are not already core contributors.

Right now I can think of these as the potential leads for these modules (checkbox means they've agreed). PLEASE suggest leads for the other modules or alternative leads if you know that someone else is more involved/has more time/whatever in a module. @AmpersandJS/core-team ( don't know if community-team is a team I can @ mention)

<strike>strikeout means the project has been edited to list the lead</strike>
- [x] ampersand-state: @latentflip 
- [x] <strike>ampersand-view-switcher: @kamilogorek</strike>
- [x] <strike>ampersand-cli: @fyockm</strike>
- [x] <strike>ampersand-form-view: @wraithgar</strike>
- [x] <strike>ampersand-input-view: @cdaringe</strike>
- [x] <strike>ampersand-select-view: @cdaringe</strike>
- [ ] tools.ampersandjs.com: (I feel like this already has someone assigned to this role?)
- [x] amp: @HenrikJoreteg 
- [x] <strike>examples @fyockm</strike>

**Comment by mike-engel** [comment]
+1 from a user of ampersand

**Comment by mrDarcyMurphy** [comment]
+1 from me as well.

**Comment by HenrikJoreteg** [comment]
Yeah, we've discussed this in the past but I think formalizing it will help people feel empowered to take ownership.

**Comment by wraithgar** [comment]
- [ ] amp: @HenrikJoreteg

**Comment by fyockm** [comment]
+1 from me. Would definitely be nice to have a specific contact on particular modules.

I'd be happy to take on lead maintainer for the CLI. I already fill that role for [AmpersandJS/examples](https://github.com/AmpersandJS/examples), which you might want to add to the list?

**Comment by cdaringe** [comment]
@wraithgar, I'd be grateful for the opportunity.  I'd be willing to on either package

**Comment by ferdinandsalis** [comment]
:+1: sounds great!

**Comment by kamilogorek** [comment]
@AmpersandJS/core-team list of all available modules on github in alphabetical order:
```sh
http https://api.github.com/orgs/AmpersandJS/repos | python -mjson.tool | grep \"name\" | grep -w ampersand | awk -F\" '{print $4}' | sort
```

- [ ] ampersand
- [ ] ampersand-array-input-view
- [ ] ampersand-checkbox-view
- [ ] ampersand-class-extend
- [ ] ampersand-collection
- [ ] ampersand-collection-rest-mixin
- [ ] ampersand-collection-underscore-mixin
- [ ] ampersand-collection-view
- [ ] ampersand-dom
- [ ] ampersand-dom-bindings
- [ ] ampersand-domthing-mixin
- [ ] ampersand-form-view
- [ ] ampersand-input-view
- [ ] ampersand-model
- [ ] ampersand-registry
- [ ] ampersand-rest-collection
- [ ] ampersand-router
- [ ] ampersand-select-view
- [ ] ampersand-state
- [ ] ampersand-subcollection
- [ ] ampersand-sync
- [ ] ampersand-view
- [ ] ampersand-view-conventions
- [ ] ampersand-view-switcher
- [ ] ampersand-webcam-snapshot-view

**Comment by nickryall** [comment]
+1 from me. 

@wraithgar Thanks for the opportunity. For now I'd prefer to keep contributing until I become more familiar and confident with the code and processes. Then I'd be more than happy to take on responsibility for a module.

**Comment by wraithgar** [comment]
This feels like it has enough traction to get started. I don't think we need to wait till we've got someone for everything to start labeling leads for the ones we have them on.

**Comment by wraithgar** [comment]
I added one to ampersand-view-switcher gonna give it a day before y'all to weigh in on the formatting just in case someone has a brilliant or strong opinion on the matter

**Comment by HenrikJoreteg** [comment]
Looks great to me. I'm excited about this.

**Comment by latentflip** [comment]
I'm happy to lead on state :+1: :)

**Comment by fyockm** [comment]
Will lead maintainers be granted the "collaborator" role, so they're able to merge PRs? Obviously, the ability to publish to `npm` is a separate privilege.

**Comment by HenrikJoreteg** [comment]
@fyockm yes, indeed. Likely npm as well.

**Comment by wraithgar** [comment]
Update: current consensus is yes on collaborator role, no on npm (for now, we want a better npm publishing process first).  So if you're a lead w/o git merge access speak up.

**Comment by cdaringe** [comment]
@wraithgar, no access yet, both modules

**Comment by wraithgar** [comment]
Ok well as I went in to try to grant that access I found myself a little lost and think I will defer to @bear how he thinks this access should be granted.

**Comment by HenrikJoreteg** [comment]
I'm not worried about fine grain access here, we work with too many security folks ([ahem](https://liftsecurity.io/)), this is open source :) 

You should have access now, @cdaringe

**Comment by HenrikJoreteg** [comment]
also, the only reason to hold off on npm publish rights, IMO, is until we create a proper release script that we all use, just to make sure the process is consistent.

**Comment by bear** [comment]
@cdaringe has been added to the community leader team and those repos have been added to the team's access

**Comment by cdaringe** [comment]
great, thanks folks.  fear not, i'll be a good steward :smile:

**Comment by fyockm** [comment]
@bear could you add me as a collaborator for this repo please? Thanks!

**Comment by bear** [comment]
@fyockm done
