### ISSUE TITLE
CLI-generated form fails with TypeError

### ISSUE THREAD

**Issue by e2jk** [AmpersandJS/ampersand#97]
I've used the CLI to create a form from a new model. When going to the page to add a new record, the following exception is logged in the console: `TypeError: this.model is null`

I have noticed that the form created with the demo app are set up like this:

    value: this.model && this.model.firstName,

whereas the CLI-generated forms have the following:

    value: this.model.name || "",

Changing the `value` to the first form solves this issue. Is there any reason against updating the CLI to generate code in that way?

**Comment by bear** [comment]
That sounds like a great Pull Request to make - go for it

**Comment by e2jk** [comment]
I had some trouble finding the exact spot, but https://github.com/AmpersandJS/ampersand/pull/99 is now ready for your review.
